target-version = "py39"
line-length = 100

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[lint]
select = ["E", "F", "I", "N", "W", "UP", "B", "SIM"]
ignore = ["E501", "UP045"]

[lint.per-file-ignores]
"__init__.py" = ["F401"]
"scripts/*" = ["SIM"]
