CORRECTIONS = {
    "depresi": "DPRD",
    "apbd": "APBD",
    "perda": "Perda",
    "permendagri": "Permendagri",
    "musrembang": "Musrenbang",
    "renja": "Renja",
    "renstra": "Renstra",
    "rpjmd": "RPJMD",
    "tupoksi": "TUPOKSI",
    "dpa": "DPA",
    "kua ppas": "KUA-PPAS",
    "kua-pas": "KUA-PPAS",
    "spj": "SPJ",
    "lpj": "LPJ",
    "spm": "SPM",
    "sekda": "Sekda",
    "kadis": "Kadis",
    "kabid": "Kabid",
    "bappeda": "BAPPEDA",
    "bpkad": "BPKAD",
    "inspektorat": "Inspektorat",
    "apip": "APIP",
    "sakip": "SAKIP",
    "lkpd": "LKPD",
    "kulti": "Kabupaten",
    "kabupatin": "Kabupaten",
    "kabupatn": "Kabupaten",
    "kabupeten": "Kabupaten",
    "kecamatan": "Kecamatan",
    "kecamatin": "Kecamatan",
    "provinsi": "Provinsi",
    "provins": "Provinsi",
    "pemprov": "Pemprov",
    "pemkab": "Pemkab",
    "pemdes": "Pemdes",
    "pemerintah": "Pemerintah",
    "pemerintah daerah": "Pemerintah Daerah",
    "pemda": "Pemda",
    "gubernur": "Gubernur",
    "bupati": "Bupati",
    "walikota": "Wali Kota",
    "walkot": "Wali Kota",
    "camat": "Camat",
    "lurah": "Lurah",
    "kades": "Kades",
    "sekretaris": "Sekretaris",
    "sekretaris daerah": "Sekretaris Daerah",
    "asisten": "Asisten",
    "kepala dinas": "Kepala Dinas",
    "kepala bidang": "Kepala Bidang",
    "kepala seksi": "Kepala Seksi",
    "kasie": "Kasie",
    "kasubag": "Kasubag",
    "kabag": "Kabag",
    "acrbpr": "BPN",
    "bpn": "BPN",
    "bpbd": "BPBD",
    "bpjs": "BPJS",
    "bpkp": "BPKP",
    "bkpm": "BKPM",
    "bkpp": "BKPP",
    "bkn": "BKN",
    "bkd": "BKD",
    "bkpsdm": "BKPSDM",
    "bappeda litbang": "Bappeda Litbang",
    "kesbangpol": "Kesbangpol",
    "satpol pp": "Satpol PP",
    "dinporabudpar": "Disporabudpar",
    "diknas": "Diknas",
    "dinkes": "Dinkes",
    "dinsos": "Dinsos",
    "dinpertan": "Dinpertan",
    "disperindag": "Disperindag",
    "disnakertrans": "Disnakertrans",
    "dpupr": "DPUPR",
    "dputr": "DPUTR",
    "dcktr": "DCKTR",
    "dlh": "DLH",
    "dishub": "Dishub",
    "disdag": "Disdag",
    "anggaran": "Anggaran",
    "apbd perubahan": "APBD Perubahan",
    "apbd murni": "APBD Murni",
    "pembahasan": "Pembahasan",
    "rapat": "Rapat",
    "sidang": "Sidang",
    "pleno": "Pleno",
    "komisi": "Komisi",
    "fraksi": "Fraksi",
    "ketua": "Ketua",
    "ketua rapat": "Ketua Rapat",
    "wakil ketua": "Wakil Ketua",
    "anggota": "Anggota",
    "pimpinan": "Pimpinan",
    "rapat dengar pendapat": "Rapat Dengar Pendapat",
    "rdp": "RDP",
    "fit and proper test": "Uji Kelayakan dan Kepatutan",
    "musdes": "Musdes",
    "musdus": "Musdus",
    "muskel": "Muskel",
    "musrenbangdes": "Musrenbangdes",
    "musrenbangcam": "Musrenbangcam",
    "musrenbangkab": "Musrenbang Kabupaten",
    "musrenbangprov": "Musrenbang Provinsi",
    "peraturan daerah": "Peraturan Daerah",
    "peraturan bupati": "Peraturan Bupati",
    "peraturan walikota": "Peraturan Wali Kota",
    "peraturan gubernur": "Peraturan Gubernur",
    "perbup": "Perbup",
    "perwal": "Perwal",
    "pergub": "Pergub",
}


def correct_terms(text: str) -> str:
    if not text:
        return text
    result = text
    for wrong, correct in CORRECTIONS.items():
        if wrong in result:
            result = result.replace(wrong, correct)
    return result


def correct_transcript(merged: list[dict]) -> list[dict]:
    for seg in merged:
        if "text" in seg and seg["text"]:
            seg["text"] = correct_terms(seg["text"])
    return merged
